require 'satre/version'
require 'satre/expression'
require 'satre/lexer'
require 'satre/and'
require 'satre/atom'
require 'satre/false'
require 'satre/formula'
require 'satre/iff'
require 'satre/imp'
require 'satre/not'
require 'satre/or'
require 'satre/true'
require 'satre/parser'
require 'satre/formula_parser'
require 'satre/expression_parser'

